services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "FABRIC"
      EULA: "TRUE"
      FABRIC_LAUNCHER_URL: "https://meta.fabricmc.net/v2/versions/loader/1.20.1/0.15.11/1.0.1/server/jar"
      MEMORY: "8G"
      INIT_MEMORY: "8G"
      MAX_MEMORY: "8G"
      DIFFICULTY: "hard"
    volumes:
      - ./minecraft:/data
    restart: unless-stopped